using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1649", Justification = "Not needed for this namespace", Scope = "Namespace", Target = "~N:GameStore.Api")]

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1121", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1500", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1201", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1028", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1116", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1028", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1117", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1116", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1111", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1009", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1513", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1009", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1405", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1306", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1203", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1204", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1507", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1005", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SX1309", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1202", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1118", Justification = "Not needed for this folder", Scope = "NamespaceAndDescendants", Target = "~N:GameStore.Api.Areas")]
